from typing import Any, Optional

from app.models.recommendation_cache import (
    RecommendationCache,
    StoredRecommendationCache,
)
from app.repositories.dynamodb_base import BaseDynamoDBRepository


class RecommendationCacheRepository(BaseDynamoDBRepository):
    """CRUD persistence for the RecommendationCache table."""

    def __init__(
        self,
        *,
        table_name: str,
        region_name: str,
        table: Any | None = None,
    ) -> None:
        super().__init__(
            table_name=table_name,
            region_name=region_name,
            table=table,
        )

    def create(self, cache_entry: RecommendationCache) -> RecommendationCache:
        return self._create(
            cache_entry,
            partition_key="user_id",
            sort_key="scenario",
        )

    def get(
        self,
        user_id: str,
        scenario: str,
    ) -> Optional[RecommendationCache]:
        stored = self._get(
            key={
                "user_id": user_id,
                "scenario": scenario,
            },
            model_type=StoredRecommendationCache,
        )
        if stored is None:
            return None
        if (
            stored.source_provider
            and "mock" in stored.source_provider.casefold()
        ):
            # Never serve rankings previously generated by the removed mock
            # provider. The record remains untouched in DynamoDB.
            return None
        return stored.to_canonical()

    def update(self, cache_entry: RecommendationCache) -> RecommendationCache:
        return self._update(
            cache_entry,
            partition_key="user_id",
            sort_key="scenario",
        )

    def upsert(self, cache_entry: RecommendationCache) -> RecommendationCache:
        """Create or fully replace one cache record without ranking decisions."""

        return self._upsert(cache_entry)

    def delete(self, user_id: str, scenario: str) -> bool:
        return self._delete(
            key={
                "user_id": user_id,
                "scenario": scenario,
            }
        )
